### ISSUE TITLE
Initialize django middleware

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/django-middleware#2]
Middlewares are needed to quickly integrate UniAuth into various languages.

This can be helpful:
https://docs.djangoproject.com/en/3.1/topics/http/middleware/

Read [how to develop this middleware here](https://github.com/UniAuth/UniAuth/wiki)

**Comment by harshil15999** [comment]
how to get assigned to this issue? @YashKumarVerma

**Comment by YashKumarVerma** [comment]
If you are willing to work on this, I'll assign you.

**Comment by harshil15999** [comment]
Yes ! Also is it necessary to do it in django or flask is ok?

**Comment by YashKumarVerma** [comment]
> Yes ! Also is it necessary to do it in django or flask is ok?

for flask, we have a separate project : https://github.com/UniAuth/flask-middleware

**Comment by MASTERCHIEF011** [comment]
pls assign this to me

**Comment by MASTERCHIEF011** [comment]
also do we need to use the built in middleware classes or should we build a custom middleware

**Comment by subhangi2731** [comment]
can you please assign it to me?

**Comment by SwarupKharul** [comment]
Hey!! I am GSSoC participant and would like to solve this issue. Please assign this issue to me under GSSoC.

**Comment by subhangi2731** [comment]
I am working on this @YashKumarVerma but I have a doubt where can I reach you??

**Comment by YashKumarVerma** [comment]
> I am working on this @YashKumarVerma but I have a doubt where can I reach you??

please reach out on discord, we have a channel named `#uniauth` in the GSSoC Server

**Comment by YashKumarVerma** [comment]
any updates @subhangi2731
